### ISSUE TITLE
Bot de WhatsApp ticket vehículos 

### ISSUE THREAD

**Issue by santiigb** [Yo-Pido-Y-Yo-pago/Mercadeo-#23]
## URL 
https://www.figma.com/board/ahiYxMdgp3ouuGjCGuv1Er/Welcome-to-FigJam?node-id=0-1&node-type=canvas&t=o2bxW3EJlNtG42r5-0

**Comment by alepsantana** [comment]
Copis ajustando enviados a IT para modificación
